import "@/sass/style.scss";
import Providers from "./components/Providers";
import SigninButton from "./components/SigninButton";

export const metadata = {
    title: "Countduck481",
    description: "Generated by create next app",
};
export async function generateStaticParams() {
    return [{ lang: "en-US" }, { lang: "de" }];
}

export default function RootLayout({ children, params }) {
    return (
        <html lang="vi">
            <body>
                <Providers>
                    <div className="theme">{children}</div>
                </Providers>
            </body>
        </html>
    );
}
